// clang -O3 -o bench bench.c -L target/release -lmanticoresearch_text_embeddings
// for static
// clang -flto -c -O2 bench.c &&  clang -flto -O3 -o bench bench.o -Ltarget/release -lmanticoresearch_text_embeddings
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>
#include "manticoresearch_text_embeddings.h"

int main() {
	const char *texts[] = {
		"This is a sample text.",
		"The quick brown fox jumps over the lazy dog.",
		"Hello, world!",
		"Artificial intelligence is the future.",
		"I love programming in C.",
		"The sun rises in the east and sets in the west.",
		"Laughter is the best medicine.",
		"Teamwork makes the dream work.",
		"Knowledge is power.",
		"Time flies when you're having fun.",
		"Rome wasn't built in a day.",
		"Actions speak louder than words.",
		"Seeing is believing.",
		"An apple a day keeps the doctor away.",
		"Curiosity killed the cat.",
		"Beauty is in the eye of the beholder.",
		"Laughter is the best medicine.",
		"A stitch in time saves nine.",
		"The early bird catches the worm.",
		"Better late than never.",
		"Birds of a feather flock together.",
		"A rolling stone gathers no moss.",
		"When life gives you lemons, make lemonade.",
		"There's no place like home.",
		"Practice makes perfect.",
		"Necessity is the mother of invention.",
		"A penny saved is a penny earned.",
		"A friend in need is a friend indeed.",
		"Slow and steady wins the race.",
		"Where there's a will, there's a way.",
		"Honesty is the best policy.",
		"The grass is always greener on the other side.",
		"Don't judge a book by its cover.",
		"You can't make an omelet without breaking a few eggs.",
		"Silence is golden.",
		"Life is what you make it.",
		"Ignorance is bliss.",
		"Easy come, easy go.",
		"Fortune favors the bold.",
		"The pen is mightier than the sword.",
		"Absence makes the heart grow fonder.",
		"Too many cooks spoil the broth.",
		"Variety is the spice of life.",
		"All that glitters is not gold.",
		"The early bird catches the worm.",
		"Actions speak louder than words.",
		"Better late than never.",
		"Curiosity killed the cat.",
		"Don't count your chickens before they hatch.",
		"Every cloud has a silver lining.",
		"Haste makes waste.",
		"Birds of a feather flock together.",
		"Charity begins at home.",
		"All that glitters is not gold.",
		"Practice makes perfect.",
		"Rome wasn't built in a day.",
		"When the going gets tough, the tough get going.",
		"A watched pot never boils.",
		"Beggars can't be choosers.",
		"An apple a day keeps the doctor away.",
		"The grass is always greener on the other side.",
		"Out of sight, out of mind.",
		"The pen is mightier than the sword.",
		"Time flies when you're having fun.",
		"You can lead a horse to water, but you can't make it drink.",
		"Look before you leap.",
		"Absence makes the heart grow fonder.",
		"Don't judge a book by its cover.",
		"Don't put the cart before the horse.",
		"It's better to be safe than sorry.",
		"A stitch in time saves nine.",
		"There's no place like home.",
		"Too many cooks spoil the broth.",
		"A rolling stone gathers no moss.",
		"Beauty is in the eye of the beholder.",
		"A leopard cannot change its spots.",
		"Killing two birds with one stone.",
		"A little knowledge is a dangerous thing.",
		"The squeaky wheel gets the grease.",
		"Money doesn't grow on trees.",
		"A journey of a thousand miles begins with a single step.",
		"Nothing ventured, nothing gained.",
		"Necessity is the mother of invention.",
		"You can't judge a book by its cover.",
		"A chain is only as strong as its weakest link.",
		"A leopard cannot change its spots.",
		"Actions speak louder than words.",
		"All good things must come to an end.",
		"All's well that ends well.",
		"All that glitters is not gold.",
		"This is a sample text.",
		"The quick brown fox jumps over the lazy dog.",
		"Hello, world!",
		"Artificial intelligence is the future.",
		"I love programming in C.",
		"The sun rises in the east and sets in the west.",
		"Laughter is the best medicine.",
		"Teamwork makes the dream work.",
		"Knowledge is power.",
		"Time flies when you're having fun.",
		"Rome wasn't built in a day.",
		"Actions speak louder than words.",
		"Seeing is believing.",
		"An apple a day keeps the doctor away.",
		"Curiosity killed the cat.",
		"Beauty is in the eye of the beholder.",
		"Laughter is the best medicine.",
		"A stitch in time saves nine.",
		"The early bird catches the worm.",
		"Better late than never.",
		"Birds of a feather flock together.",
		"A rolling stone gathers no moss.",
		"When life gives you lemons, make lemonade.",
		"There's no place like home.",
		"Practice makes perfect.",
		"Necessity is the mother of invention.",
		"A penny saved is a penny earned.",
		"A friend in need is a friend indeed.",
		"Slow and steady wins the race.",
		"Where there's a will, there's a way.",
		"Honesty is the best policy.",
		"The grass is always greener on the other side.",
		"Don't judge a book by its cover.",
		"You can't make an omelet without breaking a few eggs.",
		"Silence is golden.",
		"Life is what you make it.",
		"Ignorance is bliss.",
		"Easy come, easy go.",
		"Fortune favors the bold.",
		"The pen is mightier than the sword.",
		"Absence makes the heart grow fonder.",
		"Too many cooks spoil the broth.",
		"Variety is the spice of life.",
		"All that glitters is not gold.",
		"The early bird catches the worm.",
		"Actions speak louder than words.",
		"Better late than never.",
		"Curiosity killed the cat.",
		"Don't count your chickens before they hatch.",
		"Every cloud has a silver lining.",
		"Haste makes waste.",
		"Birds of a feather flock together.",
		"Charity begins at home.",
		"All that glitters is not gold.",
		"Practice makes perfect.",
		"Rome wasn't built in a day.",
		"When the going gets tough, the tough get going.",
		"A watched pot never boils.",
		"Beggars can't be choosers.",
		"An apple a day keeps the doctor away.",
		"The grass is always greener on the other side.",
		"Out of sight, out of mind.",
		"The pen is mightier than the sword.",
		"Time flies when you're having fun.",
		"You can lead a horse to water, but you can't make it drink.",
		"Look before you leap.",
		"Absence makes the heart grow fonder.",
		"Don't judge a book by its cover.",
		"Don't put the cart before the horse.",
		"It's better to be safe than sorry.",
		"A stitch in time saves nine.",
		"There's no place like home.",
		"Too many cooks spoil the broth.",
		"A rolling stone gathers no moss.",
		"Beauty is in the eye of the beholder.",
		"A leopard cannot change its spots.",
		"Killing two birds with one stone.",
		"A little knowledge is a dangerous thing.",
		"The squeaky wheel gets the grease.",
		"Money doesn't grow on trees.",
		"A journey of a thousand miles begins with a single step.",
		"Nothing ventured, nothing gained.",
		"Necessity is the mother of invention.",
		"You can't judge a book by its cover.",
		"A chain is only as strong as its weakest link.",
		"A leopard cannot change its spots.",
		"Actions speak louder than words.",
		"All good things must come to an end.",
		"All's well that ends well.",
		"All that glitters is not gold.",
		"This is a sample text.",
		"The quick brown fox jumps over the lazy dog.",
		"Hello, world!",
		"Artificial intelligence is the future.",
		"I love programming in C.",
		"The sun rises in the east and sets in the west.",
		"Laughter is the best medicine.",
		"Teamwork makes the dream work.",
		"Knowledge is power.",
		"Time flies when you're having fun.",
		"Rome wasn't built in a day.",
		"Actions speak louder than words.",
		"Seeing is believing.",
		"An apple a day keeps the doctor away.",
		"Curiosity killed the cat.",
		"Beauty is in the eye of the beholder.",
		"Laughter is the best medicine.",
		"A stitch in time saves nine.",
		"The early bird catches the worm.",
		"Better late than never.",
		"Birds of a feather flock together.",
		"A rolling stone gathers no moss.",
		"When life gives you lemons, make lemonade.",
		"There's no place like home.",
		"Practice makes perfect.",
		"Necessity is the mother of invention.",
		"A penny saved is a penny earned.",
		"A friend in need is a friend indeed.",
		"Slow and steady wins the race.",
		"Where there's a will, there's a way.",
		"Honesty is the best policy.",
		"The grass is always greener on the other side.",
		"Don't judge a book by its cover.",
		"You can't make an omelet without breaking a few eggs.",
		"Silence is golden.",
		"Life is what you make it.",
		"Ignorance is bliss.",
		"Easy come, easy go.",
		"Fortune favors the bold.",
		"The pen is mightier than the sword.",
		"Absence makes the heart grow fonder.",
		"Too many cooks spoil the broth.",
		"Variety is the spice of life.",
		"All that glitters is not gold.",
		"The early bird catches the worm.",
		"Actions speak louder than words.",
		"Better late than never.",
		"Curiosity killed the cat.",
		"Don't count your chickens before they hatch.",
		"Every cloud has a silver lining.",
		"Haste makes waste.",
		"Birds of a feather flock together.",
		"Charity begins at home.",
		"All that glitters is not gold.",
		"Practice makes perfect.",
		"Rome wasn't built in a day.",
		"When the going gets tough, the tough get going.",
		"A watched pot never boils.",
		"Beggars can't be choosers.",
		"An apple a day keeps the doctor away.",
		"The grass is always greener on the other side.",
		"Out of sight, out of mind.",
		"The pen is mightier than the sword.",
		"Time flies when you're having fun.",
		"You can lead a horse to water, but you can't make it drink.",
		"Look before you leap.",
		"Absence makes the heart grow fonder.",
		"Don't judge a book by its cover.",
		"Don't put the cart before the horse.",
		"It's better to be safe than sorry.",
		"A stitch in time saves nine.",
		"There's no place like home.",
		"Too many cooks spoil the broth.",
		"A rolling stone gathers no moss.",
		"Beauty is in the eye of the beholder.",
		"A leopard cannot change its spots.",
		"Killing two birds with one stone.",
		"A little knowledge is a dangerous thing.",
		"The squeaky wheel gets the grease.",
		"Money doesn't grow on trees.",
		"A journey of a thousand miles begins with a single step.",
		"Nothing ventured, nothing gained.",
		"Necessity is the mother of invention.",
		"You can't judge a book by its cover.",
		"A chain is only as strong as its weakest link.",
		"A leopard cannot change its spots.",
		"Actions speak louder than words.",
		"All good things must come to an end.",
		"All's well that ends well.",
		"All that glitters is not gold.",
		"This is a sample text.",
		"The quick brown fox jumps over the lazy dog.",
		"Hello, world!",
		"Artificial intelligence is the future.",
		"I love programming in C.",
		"The sun rises in the east and sets in the west.",
		"Laughter is the best medicine.",
		"Teamwork makes the dream work.",
		"Knowledge is power.",
		"Time flies when you're having fun.",
		"Rome wasn't built in a day.",
		"Actions speak louder than words.",
		"Seeing is believing.",
		"An apple a day keeps the doctor away.",
		"Curiosity killed the cat.",
		"Beauty is in the eye of the beholder.",
		"Laughter is the best medicine.",
		"A stitch in time saves nine.",
		"The early bird catches the worm.",
		"Better late than never.",
		"Birds of a feather flock together.",
		"A rolling stone gathers no moss.",
		"When life gives you lemons, make lemonade.",
		"There's no place like home.",
		"Practice makes perfect.",
		"Necessity is the mother of invention.",
		"A penny saved is a penny earned.",
		"A friend in need is a friend indeed.",
		"Slow and steady wins the race.",
		"Where there's a will, there's a way.",
		"Honesty is the best policy.",
		"The grass is always greener on the other side.",
		"Don't judge a book by its cover.",
		"You can't make an omelet without breaking a few eggs.",
		"Silence is golden.",
		"Life is what you make it.",
		"Ignorance is bliss.",
		"Easy come, easy go.",
		"Fortune favors the bold.",
		"The pen is mightier than the sword.",
		"Absence makes the heart grow fonder.",
		"Too many cooks spoil the broth.",
		"Variety is the spice of life.",
		"All that glitters is not gold.",
		"The early bird catches the worm.",
		"Actions speak louder than words.",
		"Better late than never.",
		"Curiosity killed the cat.",
		"Don't count your chickens before they hatch.",
		"Every cloud has a silver lining.",
		"Haste makes waste.",
		"Birds of a feather flock together.",
		"Charity begins at home.",
		"All that glitters is not gold.",
		"Practice makes perfect.",
		"Rome wasn't built in a day.",
		"When the going gets tough, the tough get going.",
		"A watched pot never boils.",
		"Beggars can't be choosers.",
		"An apple a day keeps the doctor away.",
		"The grass is always greener on the other side.",
		"Out of sight, out of mind.",
		"The pen is mightier than the sword.",
		"Time flies when you're having fun.",
		"You can lead a horse to water, but you can't make it drink.",
		"Look before you leap.",
		"Absence makes the heart grow fonder.",
		"Don't judge a book by its cover.",
		"Don't put the cart before the horse.",
		"It's better to be safe than sorry.",
		"A stitch in time saves nine.",
		"There's no place like home.",
		"Too many cooks spoil the broth.",
		"A rolling stone gathers no moss.",
		"Beauty is in the eye of the beholder.",
		"A leopard cannot change its spots.",
		"Killing two birds with one stone.",
		"A little knowledge is a dangerous thing.",
		"The squeaky wheel gets the grease.",
		"Money doesn't grow on trees.",
		"A journey of a thousand miles begins with a single step.",
		"Nothing ventured, nothing gained.",
		"Necessity is the mother of invention.",
		"You can't judge a book by its cover.",
		"A chain is only as strong as its weakest link.",
		"A leopard cannot change its spots.",
		"Actions speak louder than words.",
		"All good things must come to an end.",
		"All's well that ends well.",
		"All that glitters is not gold.",
		"Haste makes waste."
	};
	const int num_texts = sizeof(texts) / sizeof(texts[0]);

	clock_t start = clock();

	// Create a new TextEmbeddings instance
	TextEmbeddings *embeddings = malloc(sizeof(TextEmbeddings));
	if (embeddings == NULL) {
		printf("Failed to allocate memory for TextEmbeddings instance.\n");
		return 1;
	}

	*embeddings = new("sentence-transformers/multi-qa-MiniLM-L6-cos-v1", 47);

	clock_t end = clock();
	double load_time = ((double)(end - start)) * 1000.0 / CLOCKS_PER_SEC;

	printf("Time for loading model: %f milliseconds\n", load_time);

	double total_time = 0.0;
	for (int i = 0; i < num_texts; i++) {
		const char *text = texts[i];
		uintptr_t text_len = strlen(text);

		clock_t start = clock();
		const float *embeddings_ptr = get_text_embeddings(embeddings, text, text_len);
		clock_t end = clock();

		if (embeddings_ptr == NULL) {
			printf("Failed to get text embeddings.\n");
			return 1;
		}
		free((float*)embeddings_ptr);

		double time_taken = ((double)(end - start)) * 1000.0 / CLOCKS_PER_SEC;
		total_time += time_taken;

		// Print the embeddings if desired
		// const int embeddings_len = get_hidden_size(embeddings);
		// for (int j = 0; j < embeddings_len; j++) {
		//     printf("Embedding [%d]: %f\n", j, embeddings_ptr[j]);
		// }
	}

	double average_time = total_time / num_texts;
	printf("Average time for %d embeddings: %f milliseconds\n", num_texts, average_time);

	// Clean up
	free(embeddings);

	return 0;
}
